Repository Automattic/wordpress-activitypub, pull requests merged in 2023-09, with the labels that each got.

#428 Repository maintenance: add GitHub Repo Gardening action and issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/gardening.yml
Labels: [Type] Enhancement, Actions

#429 Post images: fix a typo in the hook name
  README.md
  includes/transformer/class-post.php
  readme.txt
Labels: [Type] Bug, Docs

#433 Fix .htaccess issue with subdomain
  README.md
  readme.txt
Labels: Docs, OSS Citizen

#431 Blocks: short-circuit early on sites that do not support blocks
  README.md
  activitypub.php
  includes/functions.php
  readme.txt
Labels: [Type] Bug, [Focus] Compatibility, Docs

#438 add path to route
  README.md
  includes/class-signature.php
  readme.txt
Labels: Docs

#455 Hashtags, Mentions: Use a tag stack instead of regex for protecting tags
  includes/class-hashtag.php
  includes/class-mention.php
  tests/test-class-activitypub-hashtag.php
  tests/test-class-activitypub-mention.php
Labels: [Type] Janitorial

#458 Blocks: ensure that only a valid user can be selected
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/followers/index.asset.php
  build/followers/index.js
  src/follow-me/edit.js
  src/followers/edit.js
  src/shared/use-user-options.js
Labels: [Block] Follow Me, [Block] Followers

#453 Follow Me: truncate long blog titles and handles
  build/follow-me/block.json
  build/follow-me/style-index.css
  src/follow-me/block.json
  src/follow-me/style.scss
Labels: [Block] Follow Me

#441 More Group meta-data to play nicely with existing platforms
  includes/activity/class-activity.php
  includes/activity/class-base-object.php
  includes/model/class-application-user.php
  includes/model/class-blog-user.php
  includes/model/class-user.php
  includes/rest/class-collection.php
Labels: [Status] In Progress

#462 Move [ap_hashtags] last in post in Content
  includes/transformer/class-post.php
Labels: OSS Citizen

#468 Fixes PHP warnings and remote delete
  includes/class-signature.php
  includes/transformer/class-post.php
  templates/settings.php
  tests/test-class-activitypub-post.php
Labels: [Status] In Progress

#473 add moderators as attributed_to
  includes/model/class-blog-user.php
Labels: [Status] In Progress

#472 reduce number of checks when system cron is not used
  includes/class-health-check.php
  includes/class-scheduler.php
Labels: [Status] In Progress

#471 check if blog-user collides with a username
  includes/class-admin.php
Labels: [Status] In Progress

#461 Fix styles in Follow-Me block
  build/follow-me/style-index.css
  src/follow-me/style.scss
Labels: [Block] Follow Me, OSS Citizen

#454 Remove html_entity_decode to prevent encoding issues
  includes/transformer/class-post.php
Labels: OSS Citizen
