Repository Automattic/wordpress-activitypub, pull requests merged in 2023-10, with the labels that each got.

#477 Fix various encoding issues
  includes/model/class-blog-user.php
  includes/transformer/class-post.php
Labels: [Status] In Progress

#486 README: add missing words
  README.md
  readme.txt
Labels: [Type] Bug, Docs

#494 Blocks: better frontend UX
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/index.asset.php
  build/followers/index.js
  build/followers/view.asset.php
  build/followers/view.js
  includes/class-blocks.php
  src/follow-me/follow-me.js
  src/followers/followers.js
Labels: [Block] Follow Me, [Block] Followers

#495 Blocks: improved theme compat &c.
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/style-index.css
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/index.asset.php
  build/followers/index.js
  includes/class-blocks.php
  src/follow-me/edit.js
  src/follow-me/follow-me.js
  src/follow-me/style.scss
  src/followers/edit.js
Labels: [Block] Follow Me, [Block] Followers

#496 Follow Me: more sensible and leaner styles
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/style-index.css
  src/follow-me/edit.js
  src/follow-me/style.scss
Labels: [Block] Follow Me

#491 first draft of FEDERATION.md
  FEDERATION.md
Labels: Docs

#498 Add "Security Policy" and "Code of Conduct"
  .distignore
  CODE_OF_CONDUCT.md
  LICENSE
  SECURITY.md
Labels: Docs

#511 Fix typo "lenght" in help page
  includes/help.php
Labels: OSS Citizen

#526 Shortcodes: only register when needed
  activitypub.php
  includes/class-shortcodes.php
  includes/transformer/class-post.php
  tests/test-class-activitypub-shortcodes.php
Labels: [Status] In Progress

#528 doc(README): remove typo
  README.md
Labels: Docs, OSS Citizen

#531 fix following endpoint
  README.md
  activitypub.php
  includes/rest/class-following.php
  readme.txt
Labels: Docs

#532 improve error messages and codes
  README.md
  activitypub.php
  includes/class-signature.php
  readme.txt
Labels: Docs
