Repository Automattic/wordpress-activitypub, pull requests merged in 2023-11, with the labels that each got.

#546 More reliable way to get author and autorurl
  includes/class-shortcodes.php
  readme.txt
Labels: OSS Citizen

#549 fix: support also ISO-639-1 codes
  includes/transformer/class-post.php
Labels: WordPress.com

#557 Follow Me: improve styles for dark themes
  build/follow-me/style-index.css
  src/follow-me/style.scss
Labels: [Block] Follow Me

#497 Fix #493
  includes/rest/class-inbox.php
Labels: OSS Citizen

#502 search for followers and order the output list
  includes/model/class-follower.php
  includes/table/class-followers.php
  templates/blog-user-followers-list.php
  templates/user-followers-list.php
Labels: [Status] In Progress

#570 Check if the current post type supports ActivityPub.
  includes/functions.php
Labels: [Status] In Progress

#575 schedule delete comments of deleted actor
  includes/handler/class-delete.php
Labels: OSS Citizen

#578 Clarifying what [ap_excerpt] does
  includes/help.php
  templates/settings.php
Labels: [Status] In Progress, OSS Citizen

#579 Blocks: add alt text to avatars
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/index.asset.php
  build/followers/index.js
  build/followers/view.asset.php
  build/followers/view.js
  readme.txt
  src/follow-me/follow-me.js
  src/followers/followers.js
Labels: [Block] Follow Me, [Block] Followers
