Repository Automattic/wordpress-activitypub, pull requests merged in 2023-12, with the labels that each got.

#588 Fix sending posts to at most ten instances
  includes/collection/class-followers.php
Labels: OSS Citizen

#604 Remove deprecated classes
  README.md
  includes/model/class-post.php
  includes/peer/class-followers.php
  readme.txt
Labels: Docs

#597 Make Post-Template filterable
  README.md
  includes/transformer/class-post.php
  readme.txt
Labels: Docs

#602 Add CSS class for AP comments to allow custom designs
  README.md
  includes/class-activitypub.php
  readme.txt
Labels: Docs

#610 replace `excerpt_more` with custom filter `activitypub_excerpt_more` for better consistency
  includes/class-shortcodes.php
  tests/test-class-activitypub-shortcodes.php
Labels: OSS Citizen

#618 Add nodeinfo metadata
  includes/rest/class-nodeinfo.php
Labels: OSS Citizen

#550 Comment Federation
  README.md
  assets/js/activitypub-admin.js
  includes/activity/class-base-object.php
  includes/class-activity-dispatcher.php
  includes/class-activitypub.php
  includes/class-hashtag.php
  includes/class-mention.php
  includes/class-scheduler.php
  includes/class-shortcodes.php
  includes/class-webfinger.php
  includes/collection/class-interactions.php
  includes/functions.php
  includes/rest/class-users.php
  includes/transformer/class-attachment.php
  includes/transformer/class-base.php
  includes/transformer/class-comment.php
  includes/transformer/class-factory.php
  includes/transformer/class-post.php
  readme.txt
  templates/author-json.php
  templates/blog-json.php
  templates/comment-json.php
  templates/post-json.php
  tests/test-class-activitypub-webfinger.php
Labels: [Status] In Progress, Docs

#542 Profiles: `Update` followers when profile fields change
  README.md
  includes/class-activity-dispatcher.php
  includes/class-scheduler.php
  readme.txt
Labels: Docs

#615 show admin notice when permalink structure is plain
  includes/class-admin.php
  tests/test-class-admin.php
Labels: OSS Citizen

#617 Shared Inbox
  activitypub.php
  includes/handler/class-create.php
  includes/handler/class-delete.php
  includes/handler/class-follow.php
  includes/handler/class-undo.php
  includes/handler/class-update.php
  includes/model/class-user.php
  includes/rest/class-inbox.php
Labels: [Status] In Progress

#624 Add improved classic editor image detection
  includes/transformer/class-post.php
Labels: OSS Citizen

#625 Add readme section for "WordPress in sub directory" with different si…
  README.md
  readme.txt
Labels: Docs, OSS Citizen
