Repository Automattic/wordpress-activitypub, pull requests merged in 2024-11, with the labels that each got.

#944 Add custom Preview for "Fediverse"
  activitypub.php
  build/editor-plugin/plugin.asset.php
  build/editor-plugin/plugin.js
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/index.asset.php
  build/followers/index.js
  build/followers/view.asset.php
  build/followers/view.js
  build/remote-reply/index.asset.php
  build/remote-reply/index.js
  build/reply/index.asset.php
  build/reply/index.js
  includes/class-activitypub.php
  includes/transformer/class-post.php
  src/editor-plugin/plugin.js
  templates/post-preview.php
Labels: [Status] In Progress

#966 Fix Fediverse preview for "blog actor only" mode.
  includes/collection/class-users.php
  includes/functions.php
  includes/transformer/class-post.php
  templates/post-preview.php
Labels: OSS Citizen

#962 Support `comment_previously_approved` setting
  includes/class-comment.php
Labels: [Status] In Progress

#969 Hide sticky posts that are not public
  includes/class-activitypub.php
  includes/class-migration.php
  includes/rest/class-collection.php
  includes/rest/class-outbox.php
  tests/test-class-activitypub-migrate.php
Labels: [Status] In Progress

#974 Users: do not display submenus to users who cannot author posts
  CHANGELOG.md
  README.md
  includes/class-admin.php
Labels: [Type] Bug, Docs

#982 Imrove "FEP-b2b8: Long-form Text" support
  FEDERATION.md
  includes/transformer/class-post.php
Labels: Docs

#979 Refactor get_by_id Method Using Switch Statement for Improved Readabi…
  includes/collection/class-users.php
Labels: OSS Citizen

#985 Use version constant directly
  activitypub.php
  includes/class-admin.php
  includes/class-health-check.php
  includes/class-migration.php
Labels: [Type] Janitorial

#986 CLI: Remove meta command
  CHANGELOG.md
  activitypub.php
  includes/class-cli.php
Labels: Docs, [Type] Janitorial

#987 CLI: Remove unneeded translation functions
  CHANGELOG.md
  includes/class-cli.php
Labels: Docs, [Type] Janitorial

#968 Rename `Users`-Collection to `Actors` to be more specific
  includes/class-activity-dispatcher.php
  includes/class-admin.php
  includes/class-blocks.php
  includes/class-comment.php
  includes/class-health-check.php
  includes/class-http.php
  includes/class-migration.php
  includes/class-signature.php
  includes/class-webfinger.php
  includes/collection/class-actors.php
  includes/collection/class-extra-fields.php
  includes/collection/class-users.php
  includes/functions.php
  includes/handler/class-follow.php
  includes/handler/class-undo.php
  includes/model/class-application.php
  includes/model/class-blog.php
  includes/rest/class-actors.php
  includes/rest/class-collection.php
  includes/rest/class-followers.php
  includes/rest/class-following.php
  includes/rest/class-inbox.php
  includes/rest/class-outbox.php
  includes/table/class-followers.php
  includes/transformer/class-comment.php
  includes/transformer/class-post.php
  integration/class-enable-mastodon-apps.php
  integration/class-opengraph.php
  integration/class-webfinger.php
  templates/admin-header.php
  templates/blog-settings.php
  templates/user-json.php
  templates/user-settings.php
  templates/welcome.php
  tests/test-class-activitypub-activity-dispatcher.php
  tests/test-class-activitypub-actors-collection.php
  tests/test-class-activitypub-rest-post-signature-verification.php
  tests/test-class-activitypub-signature.php
Labels: [Type] Janitorial

#995 PHPCS: Fix phpunit files
  phpcs.xml
  phpunit.xml.dist
  tests/bootstrap.php
  tests/class-activitypub-testcase-cache-http.php
  tests/class-test-activitypub-activity-dispatcher.php
  tests/class-test-activitypub-activity.php
  tests/class-test-activitypub-actors-collection.php
  tests/class-test-activitypub-comment.php
  tests/class-test-activitypub-create-handler.php
  tests/class-test-activitypub-followers.php
  tests/class-test-activitypub-hashtag.php
  tests/class-test-activitypub-integrations.php
  tests/class-test-activitypub-interactions.php
  tests/class-test-activitypub-link.php
  tests/class-test-activitypub-mention.php
  tests/class-test-activitypub-migrate.php
  tests/class-test-activitypub-post.php
  tests/class-test-activitypub-reaction-handler.php
  tests/class-test-activitypub-replies.php
  tests/class-test-activitypub-rest-inbox.php
  tests/class-test-activitypub-rest-post-signature-verification.php
  tests/class-test-activitypub-shortcodes.php
  tests/class-test-activitypub-signature.php
  tests/class-test-activitypub-user.php
  tests/class-test-activitypub-webfinger.php
  tests/class-test-activitypub.php
  tests/class-test-admin.php
  tests/class-test-enable-mastodon-apps.php
  tests/class-test-functions.php
  tests/test-class-activitypub-create-handler.php
  tests/test-class-activitypub-shortcodes.php
  tests/test-class-enable-mastodon-apps.php
Labels: php, [Type] Janitorial

#1006 Outsource Constants to a separate file
  CHANGELOG.md
  README.md
  activitypub.php
  includes/constants.php
  readme.txt
Labels: Docs

#988 Make change log entries mandatory with every PR
  .github/workflows/changelog.yml
  CHANGELOG.md
  readme.txt
Labels: Actions, Docs

#1009 Too many READMEs
  CHANGELOG.md
  FEDERATION.md
  Gruntfile.js
  README.md
  package.json
  readme.txt
Labels: Actions, Docs

#1011 Change preview showing the name instead of the preferredUsername
  CHANGELOG.md
  readme.txt
  templates/post-preview.php
Labels: OSS Citizen

#1008 Add an early return filter for `get_upload_dir()`
  CHANGELOG.md
  activitypub.php
  includes/functions.php
  readme.txt
Labels: Docs

#1024 Test with php 8.4
  .github/workflows/phpunit.yml
  tests/class-test-activitypub-actors-collection.php
Labels: Actions, Skip Changelog

#1026 Repo Gardening: automatically label more PRs, & auto-label issues
  .github/workflows/gardening.yml
Labels: [Type] Enhancement, Actions, Skip Changelog
