Repository Automattic/wordpress-activitypub, pull requests merged in 2024-12, with the labels that each got.

#1032 Update plugin URI to a8c org link
  activitypub.php
Labels: OSS Citizen, Skip Changelog

#1034 Dialog: Add screenreader labels
  CHANGELOG.md
  build/editor-plugin/plugin.asset.php
  build/editor-plugin/plugin.js
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/style-view-rtl.css
  build/follow-me/style-view.css
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/index.asset.php
  build/followers/index.js
  build/followers/view.asset.php
  build/followers/view.js
  build/remote-reply/index.asset.php
  build/remote-reply/index.js
  build/remote-reply/style-index-rtl.css
  build/remote-reply/style-index.css
  build/reply/index.asset.php
  build/reply/index.js
  includes/class-blocks.php
  readme.txt
  src/follow-me/follow-me.js
  src/shared/dialog.js
  src/shared/lightbox.scss
Labels: [Block] Follow Me, [Focus] Editor

#1038 Fix typo in custom post content settings.
  CHANGELOG.md
  readme.txt
  templates/settings.php
Labels: [Type] Bug

#1045 Add media type support
  CHANGELOG.md
  includes/transformer/class-base.php
  readme.txt
Labels: [Focus] Compatibility

#1050 Admin: Move plugin settings link into Admin class
  activitypub.php
  includes/class-admin.php
Labels: Skip Changelog

#1052 Integrations: Use Autoloader
  integration/load.php
Labels: [Status] In Progress, [Focus] Compatibility, Skip Changelog

#1055 Tests: Move autoloader into correct folder.
  tests/includes/class-test-autoloader.php
Labels: Skip Changelog

#1065 Improve Interactions moderation
  CHANGELOG.md
  includes/class-admin.php
  integration/class-akismet.php
  integration/load.php
  readme.txt
  tests/integration/class-test-akismet.php
Labels: [Status] In Progress, [Focus] Compatibility

#1053 This adds Icon support for Audio and Video attachments
  CHANGELOG.md
  includes/functions.php
  includes/transformer/class-post.php
  integration/class-seriously-simple-podcasting.php
  readme.txt
  tests/includes/transformer/class-test-post.php
Labels: [Focus] Compatibility

#1071 Remove asset updater
  .github/workflows/update-assets.yml
Labels: Actions, Skip Changelog

#1076 Blocks: Avoid PHP warning in Reply block
  CHANGELOG.md
  includes/class-blocks.php
  readme.txt
  tests/includes/class-test-blocks.php
Labels: [Type] Bug, [Focus] Editor

#1072 Improved comment-type handling
  CHANGELOG.md
  includes/class-admin.php
  includes/class-comment.php
  includes/collection/class-interactions.php
  readme.txt
  tests/includes/class-test-comment.php
Labels: [Feature] Collections

#1083 Tests: Make it easier to run unit tests locally
  .wp-env.json
  composer.json
  package.json
  tests/bootstrap.php
Labels: Skip Changelog

#1070 Add a reaction block
  CHANGELOG.md
  activitypub.php
  build/editor-plugin/plugin.asset.php
  build/editor-plugin/plugin.js
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/index.asset.php
  build/followers/index.js
  build/followers/view.asset.php
  build/followers/view.js
  build/reactions/block.json
  build/reactions/index.asset.php
  build/reactions/index.js
  build/reactions/style-index.css
  build/reactions/view.asset.php
  build/reactions/view.js
  build/remote-reply/index.asset.php
  build/remote-reply/index.js
  build/reply/index.asset.php
  build/reply/index.js
  includes/class-blocks.php
  includes/class-comment.php
  includes/class-handler.php
  includes/constants.php
  includes/handler/class-announce.php
  includes/rest/class-post.php
  readme.txt
  src/editor-plugin/plugin.js
  src/reactions/block.json
  src/reactions/edit.js
  src/reactions/editor.scss
  src/reactions/index.js
  src/reactions/reactions.js
  src/reactions/style.scss
  src/reactions/view.js
  templates/settings.php
  tests/bootstrap.php
  tests/includes/rest/class-test-post.php
Labels: [Status] In Progress, [Block] Post settings, [Focus] Editor, [Block] Reactions, [Feature] Reactions

#1088 Version bump 4.5.0
  CHANGELOG.md
  activitypub.php
  readme.txt
Labels: Skip Changelog

#1091 Reactions block: remove `@wordpress/block-editor` direct dependency
  CHANGELOG.md
  build/reactions/index.asset.php
  build/reactions/index.js
  build/reactions/style-index-rtl.css
  build/reactions/view.asset.php
  build/reactions/view.js
  readme.txt
  src/reactions/edit.js
  src/reactions/reactions.js
Labels: [Status] In Progress, [Focus] Editor

#1019 Improve documentation
  .distignore
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  FEDERATION.md
  docs/Gemfile
  docs/Gemfile.lock
  docs/_config.yml
  docs/development-environment.md
  docs/index.md
  docs/pull-request.md
  docs/readme.md
  docs/translations.md
Labels: [Status] In Progress, Docs, Skip Changelog

#1094 Prepare 4.5.1 release
  CHANGELOG.md
  activitypub.php
  readme.txt
Labels: [Status] In Progress, Skip Changelog

#1087 PHPUnit: Fix slow tests
  phpunit.xml.dist
  tests/bootstrap.php
  tests/class-activitypub-testcase-timer.php
  tests/includes/class-test-mention.php
  tests/includes/collection/class-test-followers.php
Labels: Skip Changelog

#1099 Docs: Add missing hook documentation
  includes/class-activity-dispatcher.php
  includes/class-activitypub.php
  includes/class-comment.php
  includes/class-http.php
  includes/class-link.php
  includes/class-shortcodes.php
  includes/collection/class-extra-fields.php
  includes/functions.php
  includes/handler/class-follow.php
  includes/handler/class-update.php
  includes/model/class-blog.php
  includes/rest/class-inbox.php
  includes/rest/class-interaction.php
  includes/rest/class-nodeinfo.php
  includes/transformer/class-post.php
  templates/blog-json.php
  templates/comment-json.php
  templates/post-json.php
  templates/user-json.php
Labels: Skip Changelog, [Feature] Collections

#1102 Ensure that direct messages are only sent when the user is the recipient
  CHANGELOG.md
  includes/class-mailer.php
  readme.txt
  tests/includes/class-test-mailer.php
Labels: [Type] Bug, [Status] In Progress, [Pri] High, [Feature] Notifications

#1103 Reactions: Don't display avatar when it's empty
  CHANGELOG.md
  build/editor-plugin/plugin.asset.php
  build/editor-plugin/plugin.js
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/index.asset.php
  build/followers/index.js
  build/followers/view.asset.php
  build/followers/view.js
  build/reactions/index.asset.php
  build/reactions/index.js
  build/reactions/view.asset.php
  build/reactions/view.js
  build/remote-reply/index.asset.php
  build/remote-reply/index.js
  build/reply/index.asset.php
  build/reply/index.js
  includes/class-blocks.php
  includes/class-comment.php
  readme.txt
  src/reactions/reactions.js
Labels: [Focus] Editor

#1108 Some CSS fixes for the reactions block
  CHANGELOG.md
  build/reactions/index.asset.php
  build/reactions/index.js
  build/reactions/style-index-rtl.css
  build/reactions/style-index.css
  build/reactions/view.asset.php
  build/reactions/view.js
  readme.txt
  src/reactions/reactions.js
  src/reactions/style.scss
Labels: [Status] In Progress, [Focus] Editor

#1110 Prepare Version 4.6.0
  CHANGELOG.md
  activitypub.php
  readme.txt
Labels: Skip Changelog
