Repository Automattic/wordpress-activitypub, pull requests merged in 2024-08, with the labels that each got.

#827 Add ordering for Extra fields
  includes/class-activitypub.php
  includes/functions.php
Labels: OSS Citizen

#839 Refactor Media Handling a bit and add support for Seriously Simple Podcasting
  activitypub.php
  includes/transformer/class-post.php
  integration/class-seriously-simple-podcasting.php
  integration/load.php
Labels: [Status] In Progress

#849 Replace hashtags, urls and mentions in summary with links
  README.md
  activitypub.php
  includes/class-hashtag.php
  includes/class-link.php
  includes/class-mention.php
  includes/collection/class-extra-fields.php
  includes/functions.php
  readme.txt
  tests/test-class-activitypub-link.php
Labels: Docs, OSS Citizen

#857 fix link detection for extra fields when spaces after the link and fi…
  includes/collection/class-extra-fields.php
Labels: OSS Citizen

#856 Support "read more" for Activity-Summary
  includes/class-hashtag.php
  includes/class-link.php
  includes/class-mention.php
  includes/class-shortcodes.php
  includes/collection/class-extra-fields.php
  includes/functions.php
  includes/transformer/class-post.php
  tests/test-class-activitypub-shortcodes.php
Labels: [Status] In Progress
