Repository Automattic/wordpress-activitypub, pull requests merged in 2024-09, with the labels that each got.

#866 Simple Remote-Reply endpoint.
  activitypub.php
  includes/rest/class-interaction.php
  integration/class-webfinger.php
Labels: [Type] Enhancement

#874 Fix: wrong followers URL in "to" attribute of posts
  includes/transformer/class-post.php
Labels: [Status] In Progress, OSS Citizen

#883 Fixed: Content handling for Podcasts
  CHANGELOG.md
  README.md
  activitypub.php
  integration/class-seriously-simple-podcasting.php
  readme.txt
Labels: Docs

#886 Fix Extra-Fields handling
  CHANGELOG.md
  README.md
  activitypub.php
  includes/class-admin.php
  includes/collection/class-extra-fields.php
  readme.txt
Labels: Docs

#888 Added documentation for setup behind reverse proxy with Apache
  README.md
  readme.txt
Labels: Docs, OSS Citizen

#867 A CLI extention to help with manual updates, deletes and a self-destruct feature
  activitypub.php
  includes/class-cli.php
  includes/class-scheduler.php
Labels: [Status] In Progress

#847 Improve Validation
  includes/handler/class-announce.php
  includes/handler/class-create.php
  includes/rest/class-inbox.php
  includes/rest/class-server.php
  tests/test-class-activitypub-create-handler.php
  tests/test-class-activitypub-interactions.php
Labels: [Status] In Progress

#892 Follow Me/Followers: add `inherit` mode for dynamic templating
  build/follow-me/block.json
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/block.json
  build/followers/index.asset.php
  build/followers/index.js
  build/followers/view.asset.php
  build/followers/view.js
  includes/class-blocks.php
  src/follow-me/block.json
  src/follow-me/edit.js
  src/followers/block.json
  src/followers/edit.js
  src/shared/inherit-block-fallback.js
  src/shared/use-user-options.js
Labels: [Block] Follow Me, [Block] Followers

#788 Enable Mastodon Apps: support profile editing, blog user
  includes/class-admin.php
  includes/collection/class-extra-fields.php
  includes/model/class-blog.php
  includes/model/class-user.php
  integration/class-enable-mastodon-apps.php
  templates/blog-settings.php
  templates/user-settings.php
Labels: [Status] In Progress

#899 Add Screenshots of the Blocks
  .wordpress-org/screenshot-1.png
  .wordpress-org/screenshot-2.png
  .wordpress-org/screenshot-3.png
  .wordpress-org/screenshot-4.png
  .wordpress-org/screenshot-5.png
  README.md
  readme.txt
Labels: Docs

#898 fix missing `@` in Follow-Me block
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/remote-reply/index.asset.php
  build/remote-reply/index.js
  build/reply/index.asset.php
  build/reply/index.js
  includes/class-blocks.php
  src/follow-me/follow-me.js
  src/shared/dialog.js
Labels: [Block] Follow Me

#876 Add replies collection
  activitypub.php
  includes/activity/class-activity.php
  includes/class-comment.php
  includes/collection/class-followers.php
  includes/collection/class-replies.php
  includes/rest/class-collection.php
  includes/rest/class-comment.php
  includes/transformer/class-base.php
  includes/transformer/class-comment.php
  includes/transformer/class-post.php
  tests/test-class-activitypub-comment.php
  tests/test-class-activitypub-replies.php
Labels: [Status] In Progress, OSS Citizen

#905 Suggestion: Adopt WordPress PHP Coding Standards
  activitypub.php
  composer.json
  includes/activity/class-actor.php
  includes/activity/extended-object/class-event.php
  includes/class-activitypub.php
  includes/class-admin.php
  includes/class-blocks.php
  includes/class-comment.php
  includes/class-hashtag.php
  includes/class-health-check.php
  includes/class-http.php
  includes/class-link.php
  includes/class-notification.php
  includes/class-shortcodes.php
  includes/class-signature.php
  includes/class-webfinger.php
  includes/collection/class-extra-fields.php
  includes/collection/class-followers.php
  includes/collection/class-interactions.php
  includes/collection/class-replies.php
  includes/collection/class-users.php
  includes/functions.php
  includes/handler/class-create.php
  includes/handler/class-undo.php
  includes/handler/class-update.php
  includes/model/class-application.php
  includes/model/class-blog.php
  includes/model/class-follower.php
  includes/model/class-user.php
  includes/rest/class-actors.php
  includes/rest/class-comment.php
  includes/rest/class-followers.php
  includes/rest/class-following.php
  includes/rest/class-inbox.php
  includes/rest/class-nodeinfo.php
  includes/rest/class-outbox.php
  includes/rest/class-webfinger.php
  includes/transformer/class-comment.php
  includes/transformer/class-post.php
  integration/class-buddypress.php
  integration/class-enable-mastodon-apps.php
  integration/class-jetpack.php
  integration/class-nodeinfo.php
  phpcs.xml
Labels: php, [Status] Proposal, [Type] Janitorial

#910 PHPCS: Enable MissingShort Sniff
  includes/activity/class-activity.php
  includes/activity/class-actor.php
  includes/activity/class-base-object.php
  includes/activity/extended-object/class-event.php
  includes/activity/extended-object/class-place.php
  includes/transformer/class-factory.php
  phpcs.xml
Labels: php, Docs, [Type] Janitorial

#908 PHPCS: Enable NonceVerification sniff
  includes/class-blocks.php
  phpcs.xml
Labels: php, [Type] Janitorial

#906 PHPCS: Enable NotPrepared check
  includes/functions.php
  phpcs.xml
Labels: php, [Type] Janitorial

#912 PHPCS: Enable UnusedVariable sniff
  includes/class-shortcodes.php
  includes/rest/class-inbox.php
  phpcs.xml
Labels: php, [Type] Janitorial

#913 PHPCS: Enable LongNotCapital sniff
  includes/class-scheduler.php
  phpcs.xml
Labels: php, [Type] Janitorial

#914 PHPCS: Enable CommentedOutCode sniff
  includes/class-hashtag.php
  includes/class-link.php
  includes/collection/class-interactions.php
  phpcs.xml
Labels: php, [Type] Janitorial
