Repository Automattic/wordpress-activitypub, pull requests merged in 2024-02, with the labels that each got.

#645 improve federated comments
  README.md
  activitypub.php
  includes/class-activity-dispatcher.php
  includes/class-activitypub.php
  includes/class-admin.php
  includes/class-comment.php
  includes/class-migration.php
  includes/class-scheduler.php
  includes/functions.php
  includes/handler/class-create.php
  includes/transformer/class-comment.php
  readme.txt
  tests/test-class-activitypub-comment.php
Labels: [Status] In Progress, Docs

#688 Fix "Undefined variable $type in includes/class-scheduler.php on line 191"
  includes/class-scheduler.php
Labels: OSS Citizen

#683 re-add vary header
  README.md
  activitypub.php
  includes/functions.php
  readme.txt
Labels: Docs

#692 Add all repliers as Mentions
  README.md
  includes/transformer/class-comment.php
  readme.txt
Labels: [Status] In Progress, Docs

#689 Add/remote reply
  activitypub.php
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/style-index.css
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/index.asset.php
  build/followers/view.asset.php
  build/remote-reply/block.json
  build/remote-reply/index.asset.php
  build/remote-reply/index.js
  build/remote-reply/style-index.css
  includes/class-comment.php
  includes/rest/class-comment.php
  includes/rest/class-nodeinfo.php
  integration/class-enable-mastodon-apps.php
  phpcs.xml
  src/follow-me/follow-me.js
  src/follow-me/style.scss
  src/remote-reply/block.json
  src/remote-reply/index.js
  src/remote-reply/remote-reply.js
  src/remote-reply/style.scss
  src/shared/lightbox.scss
Labels: [Block] Follow Me, [Status] In Progress

#661 A better default content handling based on the Object Type
  activitypub.php
  includes/class-activitypub.php
  includes/class-admin.php
  includes/class-migration.php
  includes/transformer/class-attachment.php
  includes/transformer/class-post.php
  templates/settings.php
Labels: [Status] In Progress
