Repository Automattic/wordpress-activitypub, pull requests merged in 2024-04, with the labels that each got.

#719 Mask version number
  includes/class-http.php
  includes/functions.php
  includes/rest/class-followers.php
  includes/rest/class-following.php
  includes/rest/class-inbox.php
  includes/rest/class-nodeinfo.php
  includes/rest/class-outbox.php
Labels: [Status] In Progress

#724 fix outbox collection for blog and application user
  includes/rest/class-outbox.php
Labels: OSS Citizen

#708 Change/docs
  CHANGELOG.md
  README.md
  activitypub.php
  readme.txt
Labels: [Status] In Progress, Docs

#723 Abstract shared Dialog code
  build/follow-me/block.json
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/style-index.css
  build/follow-me/style-view.css
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/index.asset.php
  build/followers/index.js
  build/followers/view.asset.php
  build/followers/view.js
  build/remote-reply/index.asset.php
  build/remote-reply/index.js
  src/follow-me/block.json
  src/follow-me/follow-me.js
  src/follow-me/style.scss
  src/remote-reply/remote-reply.js
  src/shared/dialog.js
Labels: [Block] Follow Me
