Repository Automattic/wordpress-activitypub, pull requests merged in 2024-10, with the labels that each got.

#924 Issue templates: add new issue type option
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: [Type] Enhancement

#911 PHPCS: Enable UnusedFunctionParameter sniff
  includes/class-shortcodes.php
  includes/rest/class-collection.php
  includes/rest/class-inbox.php
  includes/rest/class-nodeinfo.php
  phpcs.xml
  tests/test-class-activitypub-shortcodes.php
Labels: php, [Type] Janitorial

#927 PHPCS: Update workflow to fail on warnings
  .github/workflows/phpcs.yml
Labels: Actions

#930 PHPCS: Include all files by default
  includes/class-notification.php
  includes/class-signature.php
  includes/collection/class-followers.php
  includes/functions.php
  includes/handler/class-announce.php
  includes/handler/class-like.php
  includes/model/class-follower.php
  includes/rest/class-outbox.php
  includes/table/class-followers.php
  includes/transformer/class-factory.php
  includes/transformer/class-post.php
  integration/load.php
  phpcs.xml
  templates/admin-header.php
  templates/blog-followers-list.php
  templates/blog-json.php
  templates/blog-settings.php
  templates/comment-json.php
  templates/post-json.php
  templates/settings.php
  templates/toolbox.php
  templates/user-followers-list.php
  templates/user-json.php
  templates/user-settings.php
  templates/welcome.php
Labels: php, [Type] Janitorial

#940 Fixfor urls and hashtags in profiles are not converted
  includes/class-hashtag.php
  includes/class-link.php
Labels: OSS Citizen

#894 Prepare `?p=<id>` and `?author=<id>` for ActivityPub
  includes/class-activity-dispatcher.php
  includes/class-activitypub.php
  includes/class-migration.php
  includes/class-signature.php
  includes/functions.php
  includes/model/class-application.php
  includes/model/class-blog.php
  includes/model/class-user.php
  includes/rest/class-collection.php
  includes/rest/class-followers.php
  includes/rest/class-following.php
  includes/transformer/class-comment.php
  includes/transformer/class-post.php
  integration/class-enable-mastodon-apps.php
  integration/class-webfinger.php
  tests/test-class-activitypub-activity-dispatcher.php
  tests/test-class-activitypub-followers.php
Labels: [Type] Enhancement, [Status] In Progress

#949 Add Fediverse-Files video to the readme
  README.md
  readme.txt
Labels: Docs

#958 Add title to content if post is a `Note`
  activitypub.php
  includes/class-admin.php
  includes/class-migration.php
  includes/class-shortcodes.php
  includes/transformer/class-post.php
  templates/settings.php
  tests/test-class-activitypub-migrate.php
Labels: [Status] In Progress

#965 transform object to URI
  includes/collection/class-interactions.php
Labels: [Status] In Progress
