Repository Automattic/wordpress-activitypub, pull requests merged in 2024-01, with the labels that each got.

#630 Improve the property names of the transformer classes
  includes/transformer/class-attachment.php
  includes/transformer/class-base.php
  includes/transformer/class-comment.php
  includes/transformer/class-post.php
Labels: OSS Citizen

#634 Address some of things found in #633
  includes/collection/class-interactions.php
  includes/handler/class-update.php
Labels: OSS Citizen

#636 Use FEP-2c59 for WebFinger reference
  FEDERATION.md
  README.md
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/index.asset.php
  build/followers/index.js
  build/followers/view.asset.php
  build/followers/view.js
  includes/activity/class-activity.php
  includes/class-blocks.php
  includes/class-webfinger.php
  includes/model/class-user.php
  includes/rest/class-users.php
  includes/rest/class-webfinger.php
  integration/class-webfinger.php
  phpcs.xml
  readme.txt
  src/follow-me/follow-me.js
  templates/user-settings.php
  templates/welcome.php
Labels: [Block] Follow Me, [Status] In Progress, Docs

#643 Fix classic editor image finding for large images
  includes/transformer/class-post.php
Labels: OSS Citizen

#650 Update class-activitypub.php
  includes/class-activitypub.php
Labels: OSS Citizen

#629 Add/event objects
  activitypub.php
  includes/activity/class-activity.php
  includes/activity/class-actor.php
  includes/activity/class-base-object.php
  includes/activity/extended-object/README.md
  includes/activity/extended-object/class-event.php
  includes/activity/extended-object/class-place.php
  includes/functions.php
  includes/model/class-application-user.php
  includes/model/class-blog-user.php
  includes/model/class-user.php
  includes/rest/class-collection.php
  includes/rest/class-followers.php
  includes/rest/class-inbox.php
  includes/rest/class-outbox.php
  includes/rest/class-server.php
  includes/rest/class-users.php
  includes/transformer/class-base.php
  templates/author-json.php
  templates/blog-json.php
  templates/post-json.php
  tests/bootstrap.php
  tests/test-class-activitypub-activity.php
  tests/test-class-admin.php
Labels: [Block] Follow Me, [Status] In Progress, Docs, OSS Citizen

#674 Enable Mastodon Apps: Implement the account endpoint for an external account
  integration/class-enable-mastodon-apps.php
  tests/bootstrap.php
  tests/test-class-enable-mastodon-apps.php
Labels: [Status] In Progress

#677 Fix #621
  includes/model/class-follower.php
Labels: OSS Citizen

#679 Add `activitypub_update_followers_number` filter
  includes/class-scheduler.php
Labels: OSS Citizen
