Repository Automattic/wordpress-activitypub, pull requests merged in 2024-07, with the labels that each got.

#786 Add the Fediverse creator of a post to opengraph
  activitypub.php
  integration/class-opengraph.php
Labels: [Status] In Progress

#780 Support Drafts!
  includes/class-scheduler.php
  includes/functions.php
  includes/transformer/class-post.php
Labels: [Status] In Progress

#797 Update dependencies
  .github/workflows/phpunit.yml
  README.md
  activitypub.php
  composer.json
  phpcs.xml
  readme.txt
Labels: [Status] In Progress, Actions, Docs

#801 Update class-create.php
  includes/handler/class-create.php
Labels: OSS Citizen

#802 Update object_id_to_comment's PHPDoc
  includes/class-comment.php
Labels: OSS Citizen

#806 Revert to @wordpress/scripts@27
  package.json
Labels: [Type] Revert

#807 Remember remote profile
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/style-view-rtl.css
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/index.asset.php
  build/followers/index.js
  build/followers/style-view-rtl.css
  build/followers/view.asset.php
  build/followers/view.js
  build/remote-reply/index.asset.php
  build/remote-reply/index.js
  build/remote-reply/style-index-rtl.css
  build/remote-reply/style-index.css
  includes/rest/class-actors.php
  includes/rest/class-comment.php
  src/follow-me/view.js
  src/followers/followers.js
  src/followers/pagination-page.js
  src/followers/view.js
  src/remote-reply/index.js
  src/remote-reply/remote-reply.js
  src/remote-reply/style.scss
  src/shared/dialog.js
  src/shared/use-remote-user.js
Labels: [Block] Follow Me, [Block] Followers

#762 Add extra fields
  FEDERATION.md
  includes/class-activitypub.php
  includes/class-admin.php
  includes/class-scheduler.php
  includes/class-webfinger.php
  includes/collection/class-users.php
  includes/functions.php
  includes/model/class-blog.php
  includes/model/class-user.php
  integration/class-buddypress.php
  templates/user-settings.php
Labels: [Status] In Progress, Docs

#805 Some Remote-Follow improvements
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/style-view-rtl.css
  build/follow-me/style-view.css
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/index.asset.php
  build/followers/index.js
  build/followers/style-view-rtl.css
  build/followers/view.asset.php
  build/followers/view.js
  build/remote-reply/index.asset.php
  build/remote-reply/index.js
  build/remote-reply/style-index-rtl.css
  build/remote-reply/style-index.css
  includes/rest/class-actors.php
  includes/rest/class-comment.php
  src/follow-me/view.js
  src/followers/followers.js
  src/followers/pagination-page.js
  src/followers/view.js
  src/remote-reply/index.js
  src/remote-reply/remote-reply.js
  src/remote-reply/style.scss
  src/shared/dialog.js
  src/shared/lightbox.scss
  src/shared/use-remote-user.js
Labels: [Block] Follow Me, [Block] Followers, [Status] In Progress

#816 Add "Header Image" support
  assets/css/activitypub-admin.css
  assets/js/activitypub-header-image.js
  includes/class-activitypub.php
  includes/class-admin.php
  includes/model/class-blog.php
  includes/model/class-user.php
  templates/admin-header.php
  templates/blog-user-followers-list.php
  templates/blog-user-settings.php
  templates/settings.php
  templates/user-settings.php
  templates/welcome.php
Labels: [Status] In Progress

#812 Tag support for Actors
  includes/model/class-blog.php
Labels: [Status] In Progress

#817 Add link header
  includes/class-activitypub.php
  includes/rest/class-actors.php
Labels: [Status] In Progress

#819 Add "reply context" support
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/index.asset.php
  build/followers/index.js
  build/followers/view.asset.php
  build/followers/view.js
  build/reply-intent/block.json
  build/reply-intent/plugin.asset.php
  build/reply-intent/plugin.js
  build/reply/block.json
  build/reply/index.asset.php
  build/reply/index.js
  includes/activity/class-activity.php
  includes/class-activity-dispatcher.php
  includes/class-activitypub.php
  includes/class-blocks.php
  includes/functions.php
  includes/transformer/class-post.php
  src/reply-intent/block.json
  src/reply-intent/plugin.js
  src/reply/block.json
  src/reply/edit.js
  src/reply/index.js
  templates/toolbox.php
  templates/welcome.php
Labels: [Status] In Progress

#829 Add line brakes to user biography
  includes/class-admin.php
Labels: OSS Citizen
