Repository Automattic/wordpress-activitypub, pull requests merged in 2025-10, with the labels that each got.

#2258 Fix release script to handle do_action_deprecated with double quotes
  bin/__tests__/release.test.js
  bin/release.js
Labels: Skip Changelog, [Feature] WP Admin

#2255 Improve NodeInfo handling and add support for FEP-0151
  .github/changelog/2255-from-description
  FEDERATION.md
  includes/rest/class-nodeinfo-controller.php
  integration/class-nodeinfo.php
  tests/includes/rest/class-test-nodeinfo-controller.php
  tests/integration/class-test-nodeinfo.php
Labels: [Focus] Compatibility, Docs, [Feature] REST API

#2254 Add detailed magic method docs to ActivityPub classes
  includes/activity/class-activity.php
  includes/activity/class-actor.php
  includes/activity/class-base-object.php
  includes/activity/class-generic-object.php
  includes/activity/extended-object/class-event.php
  includes/activity/extended-object/class-place.php
  includes/class-moderation.php
  includes/collection/class-inbox.php
  includes/collection/class-outbox.php
Labels: [Type] Janitorial, Skip Changelog, [Feature] Collections

#2256 Add FEP-3b86 Activity Intents support to WebFinger
  .github/changelog/2256-from-description
  FEDERATION.md
  includes/rest/class-interaction-controller.php
  integration/class-webfinger.php
  tests/includes/rest/class-test-webfinger-controller.php
  tests/integration/class-test-webfinger.php
Labels: [Focus] Compatibility, Docs, [Feature] REST API

#2252 Validate ActivityPub URLs in reply block before setting inReplyTo
  .github/changelog/2252-from-description
  build/reply/block.json
  build/reply/index.asset.php
  build/reply/index.js
  includes/transformer/class-post.php
  src/reply/block.json
  src/reply/edit.js
Labels: [Block] Federated reply, [Focus] Editor

#2260 Improve inbox activity type handling and tests
  .github/changelog/2260-from-description
  includes/functions.php
  includes/handler/class-inbox.php
  tests/includes/handler/class-test-inbox.php
Labels: [Status] In Progress

#2269 Remove duplicate webfinger_user_data filter
  integration/class-webfinger.php
  tests/integration/class-test-webfinger.php
Labels: [Focus] Compatibility, Skip Changelog

#2277 Fix Prettify workflow for pull requests from forks
  .github/workflows/format.yml
Labels: Actions, Skip Changelog

#2275 Tests: Avoid using `runInSeparateProcess` where possible
  tests/integration/class-test-jetpack.php
Labels: Skip Changelog

#2285 Update builds (again)
  build/editor-plugin/plugin.asset.php
  build/editor-plugin/plugin.js
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/index.asset.php
  build/followers/index.js
  build/followers/view.asset.php
  build/followers/view.js
  build/reactions/index.asset.php
  build/reactions/index.js
  build/reactions/view.asset.php
  build/reactions/view.js
  build/remote-reply/view.asset.php
  build/remote-reply/view.js
  build/reply-intent/plugin.asset.php
  build/reply-intent/plugin.js
  package-lock.json
Labels: Skip Changelog

#2290 Fix: issue #2286 – typo, improved quoting explanation, add missing i18n in advanced settings
  .github/changelog/2290-from-description
  build/editor-plugin/plugin.asset.php
  build/editor-plugin/plugin.js
  readme.txt
  src/editor-plugin/plugin.js
Labels: OSS Citizen, [Block] Post settings, [Focus] Editor, [Feature] WP Admin

#2292 Use `bp_members_get_user_url` if available for author URLs
  integration/class-buddypress.php
Labels: [Focus] Compatibility, Skip Changelog

#2300 Pass `totalItems` to `prepare_collection_response`
  .github/changelog/2300-from-description
  includes/rest/class-outbox-controller.php
  tests/phpunit/tests/includes/rest/class-test-outbox-controller.php
Labels: [Status] In Progress, [Tests] Includes Tests, [Feature] REST API
