Repository Automattic/wordpress-activitypub, pull requests merged in 2025-02, with the labels that each got.

#1241 Extra Fields: Fix rel me count
  CHANGELOG.md
  includes/collection/class-extra-fields.php
  readme.txt
  tests/includes/collection/class-test-extra-fields.php
Labels: [Status] In Progress, [Feature] Collections

#1247 Rewrite: Flush rules
  includes/class-migration.php
Labels: Skip Changelog

#1243 Fix negotiation of ActivityPub requests for custom post types
  CHANGELOG.md
  includes/class-query.php
  readme.txt
Labels: [Status] In Progress, OSS Citizen

#1261 Debugging: avoid PHP warning when actor is not set.
  CHANGELOG.md
  includes/class-debug.php
  readme.txt
Labels: [Type] Bug, [Pri] Normal

#1256 Settings: Make tabs filterable
  CHANGELOG.md
  assets/css/activitypub-admin.css
  docs/developer-docs.md
  includes/class-admin.php
  readme.txt
  templates/admin-header.php
  templates/blog-followers-list.php
  templates/blog-settings.php
  templates/settings.php
  templates/welcome.php
Labels: [Status] In Progress, Docs

#1242 Fix/Change some return types in PHPDocs
  CHANGELOG.md
  includes/class-query.php
  includes/collection/class-replies.php
  includes/transformer/class-base.php
  readme.txt
Labels: OSS Citizen, [Feature] Collections

#1265 Check if post is enabled before saving reactions
  includes/collection/class-interactions.php
  tests/includes/collection/class-test-interactions.php
Labels: Skip Changelog, [Feature] Collections

#1267 Update Following endpoint to extend WP_REST_Controller
  activitypub.php
  includes/rest/class-following-controller.php
  includes/rest/class-following.php
  tests/includes/rest/class-test-following-controller.php
Labels: Skip Changelog

#1273 Add: Show ActivityPub preview in row actions, when block editor enabled but is not used for post type.
  CHANGELOG.md
  includes/class-admin.php
  readme.txt
Labels: OSS Citizen, [Feature] Collections

#1277 Fix duplicate header
  readme.txt
Labels: Skip Changelog

#1278 Add/sent to inboxes actions
  CHANGELOG.md
  includes/class-debug.php
  includes/class-dispatcher.php
  readme.txt
Labels: Skip Changelog

#1283 Reply Block: add broader text
  CHANGELOG.md
  readme.txt
  src/reply/edit.js
Labels: [Block] Federated reply, [Focus] Editor

#1284 Improve the wording of the Reply-Block
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/view.asset.php
  build/followers/view.js
  build/reactions/index.asset.php
  build/reactions/index.js
  build/remote-reply/index.asset.php
  build/remote-reply/index.js
  build/reply/index.asset.php
  build/reply/index.js
  src/reply/edit.js
Labels: Skip Changelog, [Block] Federated reply, [Focus] Editor

#1285 Outbox Batch: Only pass outbox id to jobs
  includes/class-dispatcher.php
  tests/includes/class-test-dispatcher.php
Labels: Skip Changelog

#1262 Process Follower Inboxes in Batches
  CHANGELOG.md
  includes/class-activitypub.php
  includes/class-debug.php
  includes/class-dispatcher.php
  includes/class-scheduler.php
  includes/collection/class-followers.php
  includes/constants.php
  integration/class-stream-connector.php
  readme.txt
  tests/includes/class-test-dispatcher.php
  tests/includes/collection/class-test-followers.php
Labels: [Status] In Progress, [Focus] Compatibility, [Feature] Collections

#1305 Fix content-visibility in block editor
  CHANGELOG.md
  includes/class-blocks.php
  readme.txt
  tests/includes/class-test-functions.php
Labels: [Focus] Editor

#1303 Break up Collections endpoint and extend WP_REST_Controller
  CHANGELOG.md
  activitypub.php
  includes/activity/class-base-object.php
  includes/class-activitypub.php
  includes/class-blocks.php
  includes/collection/class-replies.php
  includes/rest/class-collection.php
  includes/rest/class-collections-controller.php
  includes/rest/class-moderators-controller.php
  includes/rest/class-replies-controller.php
  includes/transformer/class-base.php
  includes/transformer/class-comment.php
  includes/transformer/class-post.php
  readme.txt
  tests/includes/class-test-functions.php
  tests/includes/class-test-migration.php
  tests/includes/rest/class-test-collection.php
  tests/includes/rest/class-test-collections-controller.php
  tests/includes/rest/class-test-moderators-controller.php
  tests/includes/rest/class-test-replies-controller.php
Labels: Skip Changelog, [Focus] Editor, [Feature] Collections

#1308 Add rest controller for likes and shares
  CHANGELOG.md
  includes/activity/class-base-object.php
  includes/class-comment.php
  includes/class-query.php
  includes/collection/class-interactions.php
  includes/collection/class-replies.php
  includes/rest/class-replies-controller.php
  includes/transformer/class-post.php
  readme.txt
  tests/includes/rest/class-test-replies-controller.php
Labels: [Feature] Collections

#1309 Nodeinfo: Add http docs
  includes/rest/class-nodeinfo-controller.php
  tests/includes/rest/class-test-nodeinfo-controller.php
Labels: Skip Changelog

#1316 Fix CLI scheduler function
  CHANGELOG.md
  includes/class-cli.php
  readme.txt
Labels: OSS Citizen

#1288 Purge Outbox Items on Schedule
  CHANGELOG.md
  includes/class-migration.php
  includes/class-scheduler.php
  readme.txt
  tests/includes/class-test-scheduler.php
Labels: [Status] In Progress

#1307 Magic method docs
  includes/activity/class-activity.php
  includes/activity/class-actor.php
  includes/activity/class-base-object.php
  includes/class-dispatcher.php
  includes/handler/class-delete.php
  includes/model/class-application.php
  includes/model/class-blog.php
  includes/model/class-follower.php
  includes/model/class-user.php
Labels: Skip Changelog, [Feature] Collections

#1279 Add support for deprecated version replacements
  bin/release.js
Labels: Skip Changelog

#1320 Fix: Fix Comment CLI
  includes/class-cli.php
Labels: Skip Changelog

#1304 Fix: duplicate content check
  CHANGELOG.md
  includes/class-comment.php
  readme.txt
  tests/includes/class-test-comment.php
  tests/includes/class-test-functions.php
Labels: [Feature] Federated comments

#1323 Group admin-related classes
  activitypub.php
  includes/wp-admin/class-admin.php
  includes/wp-admin/class-blog-settings-fields.php
  includes/wp-admin/class-health-check.php
  includes/wp-admin/class-menu.php
  includes/wp-admin/class-settings-fields.php
  includes/wp-admin/class-settings.php
  tests/includes/wp-admin/class-test-admin.php
Labels: Skip Changelog

#1330 Fix: Uncaught Error: Call to undefined method Json::get_id
  includes/transformer/class-activity-object.php
Labels: Skip Changelog

#1301 Add Undo functionality
  CHANGELOG.md
  includes/activity/class-activity.php
  includes/activity/class-base-object.php
  includes/class-cli.php
  includes/class-dispatcher.php
  includes/collection/class-outbox.php
  includes/transformer/class-base.php
  readme.txt
  tests/includes/collection/class-test-outbox.php
Labels: [Status] In Progress, [Feature] Collections

#1292 Add URI transformer
  CHANGELOG.md
  includes/class-http.php
  includes/functions.php
  includes/transformer/class-factory.php
  readme.txt
  tests/includes/transformer/class-test-factory.php
Labels: [Status] In Progress

#1333 Settings: Bring back notifications
  includes/wp-admin/class-settings-fields.php
Labels: Skip Changelog

#1268 Fix outbox not using object types other than Base_Object
  CHANGELOG.md
  includes/activity/class-activity.php
  includes/activity/class-actor.php
  includes/activity/class-base-object.php
  includes/activity/class-generic-object.php
  includes/handler/class-follow.php
  includes/transformer/class-base.php
  readme.txt
  tests/includes/activity/class-test-activity.php
  tests/includes/activity/class-test-base-object.php
  tests/includes/activity/class-test-generic-object.php
  tests/includes/collection/class-test-outbox.php
Labels: OSS Citizen, [Block] Post settings, [Focus] Editor, [Feature] Collections

#1172 Add metadata to New Follower E-Mail
  CHANGELOG.md
  includes/class-mailer.php
  readme.txt
  templates/new-follower-email.php
Labels: [Feature] Notifications

#1258 Add support for a reply "context"
  CHANGELOG.md
  FEDERATION.md
  includes/collection/class-replies.php
  includes/rest/class-post.php
  includes/transformer/class-comment.php
  includes/transformer/class-post.php
  readme.txt
  tests/includes/collection/class-test-replies.php
Labels: [Status] In Progress, Docs, [Feature] Collections

#1342 Send Update-Activity when "Actor-Mode" is changed
  CHANGELOG.md
  includes/scheduler/class-actor.php
  readme.txt
  tests/includes/class-test-signature.php
Labels: [Status] In Progress

#1344 Settings: Move help tabs to settings class
  includes/help.php
  includes/wp-admin/class-settings.php
Labels: Skip Changelog

#1345 Editor: Add context to visibility settings
  CHANGELOG.md
  build/editor-plugin/plugin.asset.php
  build/editor-plugin/plugin.js
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/view.asset.php
  build/followers/view.js
  build/reactions/index.asset.php
  build/reactions/index.js
  build/remote-reply/index.asset.php
  build/remote-reply/index.js
  readme.txt
  src/editor-plugin/plugin.js
Labels: [Block] Post settings, [Focus] Editor

#1348 Fix: consistent use of `site_supports_blocks`
  includes/class-shortcodes.php
  includes/transformer/class-post.php
Labels: Skip Changelog

#1349 Outbox: Re-use cached inbox getters
  CHANGELOG.md
  includes/collection/class-followers.php
  readme.txt
  tests/includes/collection/class-test-followers.php
Labels: [Feature] Collections

#1335 Move: Support incoming Move Activities
  CHANGELOG.md
  includes/activity/class-actor.php
  includes/functions.php
  includes/handler/class-move.php
  includes/handler/class-update.php
  phpcs.xml
  readme.txt
  tests/includes/handler/class-test-move.php
  tests/includes/handler/class-test-update.php
Labels: [Status] In Progress

#1332 Add: Resolvable Outbox-Activities
  CHANGELOG.md
  includes/class-query.php
  includes/collection/class-actors.php
  includes/collection/class-outbox.php
  includes/rest/class-outbox-controller.php
  readme.txt
  templates/activitypub-json.php
  tests/includes/class-test-query.php
  tests/includes/rest/class-test-followers-controller.php
  tests/includes/rest/class-test-following-controller.php
  tests/includes/rest/class-test-outbox-controller.php
Labels: [Status] In Progress, [Feature] Collections, [Pri] High

#1351 Fix Announce Activities
  CHANGELOG.md
  includes/class-cli.php
  includes/class-scheduler.php
  includes/collection/class-outbox.php
  readme.txt
  tests/includes/class-test-scheduler.php
Labels: [Feature] Collections

#1358 Rewrite rules: be more specific in pattern to get author redirects
  CHANGELOG.md
  includes/class-activitypub.php
  readme.txt
Labels: [Type] Bug

#1360 Tests: Don't show Outbox in Rest API
  tests/bootstrap.php
Labels: Skip Changelog

#1367 Post representation: bring back the activitypub_post_locale filter
  CHANGELOG.md
  includes/transformer/class-post.php
  readme.txt
Labels: [Type] Bug, [Focus] Compatibility, [Pri] Normal

#1368 Upgrades: Flush rewrite rules for #1358
  includes/class-migration.php
Labels: Skip Changelog

#1369 Readme: Remove remaining 4.x changelogs
  readme.txt
Labels: Skip Changelog

#1370 Deprecate activitypub_post_locale in favor of activitypub_locale
  CHANGELOG.md
  includes/transformer/class-base.php
  includes/transformer/class-post.php
  integration/class-wpml.php
  readme.txt
Labels: [Focus] Compatibility, [Type] Janitorial, [Pri] Low

#1376 Fix #1375
  includes/wp-admin/class-settings.php
Labels: Skip Changelog

#1363 Docs: Improve type hints
  includes/activity/class-activity.php
  includes/activity/class-base-object.php
  includes/activity/class-generic-object.php
  includes/activity/extended-object/class-event.php
  includes/activity/extended-object/class-place.php
  includes/class-activitypub.php
  includes/class-query.php
  includes/class-scheduler.php
  includes/collection/class-followers.php
  includes/collection/class-outbox.php
  includes/functions.php
  includes/model/class-blog.php
  includes/model/class-follower.php
  includes/transformer/class-activity-object.php
  includes/transformer/class-base.php
  includes/transformer/class-comment.php
  includes/transformer/class-post.php
Labels: Skip Changelog, [Feature] Collections

#1382 Fix: Reply-Context link is missing
  CHANGELOG.md
  includes/transformer/class-post.php
  readme.txt
Labels: [Type] Bug, [Block] Federated reply

#1384 PHP: Remove unused imports
  includes/activity/class-activity.php
  includes/class-activitypub.php
  includes/class-mailer.php
  includes/handler/class-follow.php
  includes/rest/class-outbox-controller.php
  includes/scheduler/class-comment.php
  includes/scheduler/class-post.php
  includes/transformer/class-json.php
  includes/wp-admin/class-admin.php
Labels: Skip Changelog, [Feature] Notifications

#1386 Tests: Make it easy to get code coverage reports
  .gitignore
  .wp-env.json
  docs/development-environment.md
  includes/activity/class-base-object.php
  phpunit.xml.dist
  tests/includes/activity/class-test-base-object.php
  tests/includes/class-test-comment.php
  tests/includes/class-test-functions.php
  tests/includes/class-test-migration.php
  tests/includes/collection/class-test-extra-fields.php
  tests/includes/collection/class-test-followers.php
  tests/includes/handler/class-test-move.php
  tests/includes/handler/class-test-update.php
  tests/includes/transformer/class-test-activity-object.php
Labels: Docs, Skip Changelog

#1394 Releases: Exclude meta PRs from automated Changelog
  .github/release.yml
  bin/release.js
Labels: Skip Changelog

#1392 Docs: Add release docs
  README.md
  docs/images/release-ui-major.png
  docs/images/release-ui-patch.png
  docs/release-process.md
Labels: Docs, Skip Changelog

#1374 Add webfinger as comment author email if available
  CHANGELOG.md
  includes/class-migration.php
  includes/class-webfinger.php
  includes/collection/class-interactions.php
  readme.txt
  tests/includes/class-test-migration.php
  tests/includes/collection/class-test-interactions.php
Labels: [Feature] Collections

#1385 Admin: Move admin-specific callbacks into wp-admin
  includes/class-activitypub.php
  includes/wp-admin/class-admin.php
Labels: Skip Changelog
