Repository Automattic/wordpress-activitypub, pull requests merged in 2025-01, with the labels that each got.

#1127 Janitorial: Fix PHP Warnings
  CHANGELOG.md
  includes/collection/class-interactions.php
  includes/transformer/class-post.php
  readme.txt
  templates/post-preview.php
Labels: [Type] Janitorial, [Feature] Collections

#1104 Jetpack: Support comment management in Calypso
  CHANGELOG.md
  integration/class-jetpack.php
  readme.txt
Labels: [Type] Bug, [Focus] Compatibility, [Pri] Normal, [Feature] Reactions

#1090 Post meta: Update meta keys to be private
  CHANGELOG.md
  includes/class-activitypub.php
  includes/class-migration.php
  includes/collection/class-actors.php
  includes/collection/class-followers.php
  includes/model/class-follower.php
  includes/transformer/class-post.php
  integration/class-jetpack.php
  readme.txt
  tests/includes/class-test-migration.php
  tests/includes/collection/class-test-followers.php
  tests/includes/transformer/class-test-post.php
Labels: [Focus] Compatibility, [Block] Post settings, [Focus] Editor, [Feature] Collections

#1118 Enable Mastodon Apps: Improve Reply Fetching
  CHANGELOG.md
  includes/constants.php
  integration/class-enable-mastodon-apps.php
  readme.txt
Labels: [Focus] Compatibility

#1142 Tests: Specify port to make tests pass
  .wp-env.json
  tests/bootstrap.php
Labels: [Type] Janitorial, Skip Changelog

#1139 Bump minimum version to PHP 7.2
  .github/workflows/phpunit.yml
  CHANGELOG.md
  activitypub.php
  composer.json
  phpcs.xml
  phpunit.xml.dist
  readme.txt
  tests/includes/collection/class-test-followers.php
  tests/includes/rest/class-test-signature-verification.php
  tests/includes/transformer/class-test-post.php
Labels: Actions, [Type] Janitorial

#1137 Comments: Show @-mentions in line with reply
  CHANGELOG.md
  includes/transformer/class-comment.php
  readme.txt
  tests/includes/transformer/class-test-comment.php
Labels: [Type] Bug, [Feature] Federated comments, [Pri] Normal

#1128 Comments: Update counts when (de)activating the plugin
  CHANGELOG.md
  includes/class-activitypub.php
  readme.txt
Labels: [Feature] Federated comments

#1146 Webfinger: Use Rest Controller structure
  activitypub.php
  includes/rest/class-webfinger-controller.php
  includes/rest/class-webfinger.php
  tests/bootstrap.php
  tests/class-test-rest-controller-testcase.php
  tests/includes/rest/class-test-webfinger-controller.php
Labels: [Type] Janitorial, Skip Changelog, [Tests] Includes Tests

#1131 Frontend scripts: print options later
  CHANGELOG.md
  includes/class-blocks.php
  readme.txt
Labels: [Focus] Editor

#1145 Application: Use Rest Controller structure
  activitypub.php
  includes/rest/class-application-controller.php
  includes/rest/class-server.php
  tests/includes/rest/class-test-application-controller.php
Labels: [Type] Janitorial, Skip Changelog

#1151 Skip Changelog for Dependabot PRs
  .github/dependabot.yml
Labels: Skip Changelog

#1161 Fix missing migration for v4.7.0
  CHANGELOG.md
  activitypub.php
  includes/class-migration.php
  readme.txt
  tests/includes/class-test-migration.php
Labels: [Pri] High

#1048 Issue Templates: update bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/gardening.yml
Labels: Actions, [Type] Janitorial, Skip Changelog, [Pri] Normal

#1144 NodeInfo: Use Rest Controller structure
  CHANGELOG.md
  activitypub.php
  includes/class-activitypub.php
  includes/rest/class-nodeinfo-controller.php
  includes/rest/class-nodeinfo.php
  readme.txt
  tests/includes/rest/class-test-nodeinfo-controller.php
Labels: [Type] Janitorial

#1164 Update users => actors
  includes/collection/class-followers.php
  includes/handler/class-update.php
  tests/includes/class-test-activity-dispatcher.php
  tests/includes/class-test-mention.php
  tests/includes/collection/class-test-followers.php
Labels: Skip Changelog, [Feature] Collections

#1149 Interaction: Use Rest Controller structure
  activitypub.php
  includes/rest/class-interaction-controller.php
  tests/includes/rest/class-test-interaction-controller.php
Labels: [Type] Janitorial, Skip Changelog

#1159 Add release script
  bin/release.js
  package.json
Labels: Skip Changelog

#1173 Outbox: Use post meta instead of taxonomies
  includes/class-activitypub.php
  includes/collection/class-outbox.php
  tests/includes/class-test-activitypub.php
  tests/includes/collection/class-test-outbox.php
Labels: Skip Changelog, [Feature] Collections

#1166 Add support for WPML post locale
  CHANGELOG.md
  integration/class-wpml.php
  integration/load.php
  readme.txt
Labels: [Focus] Compatibility, OSS Citizen

#1168 Use `_activityPubOptions` at runtime
  CHANGELOG.md
  build/editor-plugin/plugin.asset.php
  build/editor-plugin/plugin.js
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/index.asset.php
  build/followers/index.js
  build/followers/view.asset.php
  build/followers/view.js
  build/reactions/index.asset.php
  build/reactions/index.js
  build/reactions/view.asset.php
  build/reactions/view.js
  build/remote-reply/index.asset.php
  build/remote-reply/index.js
  build/reply/index.asset.php
  build/reply/index.js
  includes/class-blocks.php
  readme.txt
  src/follow-me/follow-me.js
  src/followers/followers.js
  src/reactions/reactions.js
  src/remote-reply/remote-reply.js
  src/shared/inherit-block-fallback.js
  src/shared/use-options.js
  src/shared/use-user-options.js
Labels: [Block] Follow Me, [Block] Followers, [Block] Remote Reply, [Focus] Editor, [Block] Reactions, [Feature] Reactions

#1179 Releases: Replace versions in upgrade scripts
  bin/release.js
  includes/class-migration.php
Labels: Skip Changelog

#1199 Remove link to firefish
  readme.txt
Labels: Skip Changelog

#1188 Outbox: Use callbacks that can be unhooked.
  includes/scheduler/class-comment.php
  includes/scheduler/class-post.php
  includes/transformer/class-factory.php
  tests/includes/scheduler/class-test-comment.php
Labels: Skip Changelog

#1195 Outbox: Make sure Last page is linked correctly
  includes/rest/class-outbox-controller.php
  tests/includes/rest/class-test-outbox-controller.php
Labels: Skip Changelog

#1200 Outbox: Fix Query
  includes/collection/class-outbox.php
  includes/rest/class-outbox-controller.php
  tests/includes/rest/class-test-outbox-controller.php
Labels: [Focus] Compatibility, Skip Changelog, [Feature] Collections

#1196 Outbox: Tests and fixes for Post Scheduler
  includes/scheduler/class-actor.php
  includes/scheduler/class-post.php
  includes/transformer/class-factory.php
  tests/includes/scheduler/class-test-actor.php
  tests/includes/scheduler/class-test-post.php
Labels: Skip Changelog

#1207 Actions: Only run tests once
  .github/workflows/phpcs.yml
  .github/workflows/phpunit.yml
Labels: Actions, Skip Changelog

#1211 Outbox: Align return type and update docs
  includes/scheduler/class-post.php
Labels: Skip Changelog

#1212 Outbox: Fix broken HTML tags after decoding Outbox items
  includes/collection/class-outbox.php
  tests/includes/collection/class-test-outbox.php
Labels: Skip Changelog, [Feature] Collections

#1214 Outbox: Fix race condition with Post-Metas
  includes/scheduler/class-post.php
Labels: [Status] In Progress, Skip Changelog

#1178 Outbox: Generalize functionality of the transformers
  includes/activity/class-base-object.php
  includes/class-dispatcher.php
  includes/collection/class-actors.php
  includes/functions.php
  includes/scheduler/class-post.php
  includes/transformer/class-activity-object.php
  includes/transformer/class-base.php
  includes/transformer/class-comment.php
  includes/transformer/class-json.php
  includes/transformer/class-post.php
  includes/transformer/class-user.php
  tests/includes/class-test-activitypub.php
  tests/includes/class-test-comment.php
  tests/includes/class-test-hashtag.php
  tests/includes/class-test-migration.php
  tests/includes/collection/class-test-outbox.php
  tests/includes/transformer/class-test-activity-object.php
  tests/includes/transformer/class-test-post.php
Labels: [Status] In Progress, Skip Changelog, [Feature] Collections

#1215 Update/testcases
  tests/bootstrap.php
  tests/class-activitypub-outbox-testcase.php
  tests/includes/scheduler/class-test-actor.php
  tests/includes/scheduler/class-test-comment.php
  tests/includes/scheduler/class-test-post.php
Labels: Skip Changelog

#1175 Outbox: Add upgrade script to populate outbox items
  includes/class-activitypub.php
  includes/class-migration.php
  tests/includes/class-test-migration.php
Labels: [Status] In Progress, Skip Changelog

#1205 Accept Follower: Migrate to outbox
  includes/class-dispatcher.php
  includes/functions.php
  includes/handler/class-follow.php
  includes/transformer/class-json.php
  tests/includes/class-test-functions.php
  tests/includes/handler/class-test-follow.php
Labels: [Status] In Progress, Skip Changelog

#1217 Send Activity and not its object
  includes/class-dispatcher.php
  tests/includes/class-test-dispatcher.php
Labels: Skip Changelog

#1218 Outbox: fix to_id function for user transformer
  includes/transformer/class-user.php
  tests/includes/class-test-query.php
Labels: Skip Changelog

#1220 Update/pr tests
  tests/includes/collection/class-test-outbox.php
Labels: Skip Changelog

#1221 Release Script: Replace `@since` versions
  bin/release.js
Labels: Skip Changelog

#1222 Check response body for tombstone type (#1209)
  CHANGELOG.md
  includes/class-http.php
  readme.txt
  tests/includes/class-test-http.php
Labels: OSS Citizen

#1219 Outbox: Fix attachment transitions
  includes/scheduler/class-post.php
  tests/includes/scheduler/class-test-post.php
Labels: Skip Changelog

#1224 Outbox: Fix deletes
  includes/class-dispatcher.php
  includes/scheduler/class-post.php
  tests/includes/scheduler/class-test-post.php
Labels: Skip Changelog

#1225 Outbox: Publish item after processing
  includes/class-dispatcher.php
  tests/includes/class-test-dispatcher.php
Labels: Skip Changelog

#1226 Outbox: Fix `to`, `cc` and `id`
  includes/activity/class-base-object.php
  includes/rest/class-outbox-controller.php
  tests/includes/activity/class-test-base-object.php
Labels: Skip Changelog

#1228 Outbox: Register new event schedule on upgrade
  includes/class-migration.php
  includes/class-scheduler.php
Labels: Skip Changelog

#1227 Outbox: Make post type non-hierarchical
  includes/class-activitypub.php
Labels: Skip Changelog

#1230 Outbox: Account for invalid json
  includes/activity/class-base-object.php
  includes/collection/class-followers.php
  includes/model/class-follower.php
  tests/includes/activity/class-test-base-object.php
  tests/includes/collection/class-test-followers.php
Labels: Skip Changelog, [Feature] Collections

#1236 Outbox: Fix profile updates
  includes/activity/class-activity.php
Labels: Skip Changelog

#1237 Outbox: Federate blog user updates
  includes/scheduler/class-actor.php
  tests/includes/scheduler/class-test-actor.php
Labels: [Status] In Progress, Skip Changelog

#1229 Outbox: Show Outbox processing in Stream
  includes/class-dispatcher.php
  integration/class-stream-connector.php
Labels: [Focus] Compatibility, Skip Changelog

#1238 Scripts: Add generic wp-env command
  package.json
Labels: Skip Changelog
