Repository Automattic/wordpress-activitypub, pull requests merged in 2025-03, with the labels that each got.

#1399 Readme: Add upgrade notice
  readme.txt
Labels: Skip Changelog

#1401 EMA: Remove the special handling of comments
  CHANGELOG.md
  integration/class-enable-mastodon-apps.php
  readme.txt
Labels: [Focus] Compatibility

#685 Add "Move Account" functionality
  includes/activity/class-actor.php
  includes/class-activitypub.php
  includes/class-cli.php
  includes/class-move.php
  includes/collection/class-outbox.php
  includes/handler/class-delete.php
  includes/handler/class-like.php
  includes/handler/class-move.php
  includes/model/class-blog.php
  includes/model/class-user.php
  includes/wp-admin/class-admin.php
  includes/wp-admin/class-blog-settings-fields.php
  includes/wp-admin/class-settings-fields.php
  includes/wp-admin/class-settings.php
  templates/user-settings.php
  tests/includes/class-test-move.php
Labels: Skip Changelog, [Feature] Collections

#1398 Profile Settings: Use Settings API
  activitypub.php
  includes/class-activitypub.php
  includes/wp-admin/class-admin.php
  includes/wp-admin/class-user-settings-fields.php
  templates/user-settings.php
Labels: Skip Changelog, [Feature] Collections

#1412 Fix: Outgoing Move Activity
  includes/class-handler.php
  includes/class-move.php
Labels: [Status] In Progress, Skip Changelog

#1364 Update Inbox endpoints to extend WP_REST_Controller
  activitypub.php
  includes/rest/class-actors-inbox-controller.php
  includes/rest/class-inbox-controller.php
  includes/rest/class-inbox.php
  tests/includes/rest/class-test-actors-inbox-controller.php
  tests/includes/rest/class-test-inbox-controller.php
Labels: Skip Changelog

#1415 Move: Fix `get(_user)_options` handling
  includes/class-move.php
  tests/includes/class-test-move.php
  tests/includes/class-test-sanitize.php
Labels: Skip Changelog

#1414 Move: Always add all already alsoKnownAs fields
  includes/model/class-blog.php
  includes/model/class-user.php
  tests/includes/class-test-move.php
Labels: [Status] In Progress, Skip Changelog

#1423 Re-Add: Announce Updates and Deletes
  CHANGELOG.md
  includes/class-scheduler.php
  includes/collection/class-outbox.php
  readme.txt
  tests/includes/scheduler/class-test-post.php
Labels: [Feature] Collections

#1427 Replies Context: Account for single user mode
  CHANGELOG.md
  includes/collection/class-replies.php
  readme.txt
  tests/includes/collection/class-test-replies.php
Labels: [Feature] Collections

#1446 Separate init hook for WP-Admin
  activitypub.php
Labels: Skip Changelog

#1452 Release process: add Changelogger
  .github/changelog/.gitkeep
  .github/changelog/add-announces
  .github/changelog/add-changelogger
  .github/changelog/add-const-troubleshooting
  .github/changelog/add-follower-shortcut
  .github/changelog/add-move-docs
  .github/changelog/add-site-health-data
  .github/changelog/add-version-mask
  .github/changelog/fix-1437
  .github/changelog/fix-cropping-warnings
  .github/changelog/fix-cropping-warnings-2
  .github/changelog/fix-image-id
  .github/changelog/fix-title-case
  .github/changelog/fix-user-option-outbox
  .github/changelog/fix-wp-error-id
  .github/workflows/changelog.yml
  CHANGELOG.md
  bin/release.js
  composer.json
  readme.txt
Labels: [Type] Enhancement, dependencies, Actions, Release, [Status] Needs review

#1454 Docs: update to mention changelog and release changes
  .github/changelog/update-docs-pr-changelog-composer
  docs/development-environment.md
  docs/pull-request.md
  docs/release-process.md
Labels: [Type] Enhancement, Docs

#1456 Changelogger: automatically create a changelog entry from info extracted from PR description
  .github/PULL_REQUEST_TEMPLATE.md
  .github/changelog/add-changelogger-from-pr-description
  .github/workflows/changelog.yml
Labels: [Type] Enhancement, Actions, Docs, [Status] Needs review

#1461 Rest: Use utility function everywhere
  includes/class-comment.php
  includes/collection/class-replies.php
Labels: Skip Changelog, [Feature] Collections

#1462 Remove unused sanitize_url
  .github/changelog/1462-from-description
  .github/workflows/changelog.yml
  includes/functions.php
Labels: Actions

#1471 Update the text for Enable Mastodon Apps
  includes/wp-admin/class-welcome-fields.php
Labels: Skip Changelog

#1473 Actors: Add utility function to get actor type
  .github/changelog/1473-from-description
  includes/collection/class-actors.php
  includes/collection/class-outbox.php
  includes/rest/class-outbox-controller.php
  tests/includes/collection/class-test-actors.php
Labels: [Feature] Collections

#1475 Actors: Make sure user id is int before strict-checking it
  includes/collection/class-actors.php
Labels: Skip Changelog, [Feature] Collections

#1476 Release 5.5.0
  .github/changelog/1462-from-description
  .github/changelog/1465-from-description
  .github/changelog/1472-from-description
  .github/changelog/1473-from-description
  .github/changelog/add-announces
  .github/changelog/add-basic-relay-support
  .github/changelog/add-changelogger
  .github/changelog/add-changelogger-from-pr-description
  .github/changelog/add-const-troubleshooting
  .github/changelog/add-follower-shortcut
  .github/changelog/add-move-docs
  .github/changelog/add-recommended-plugins
  .github/changelog/add-site-health-data
  .github/changelog/add-version-mask
  .github/changelog/change-setting-constants
  .github/changelog/fix-1437
  .github/changelog/fix-@-name-unslashed-redirects
  .github/changelog/fix-carousel-block
  .github/changelog/fix-cropping-warnings
  .github/changelog/fix-cropping-warnings-2
  .github/changelog/fix-follow-me-button
  .github/changelog/fix-image-id
  .github/changelog/fix-query
  .github/changelog/fix-title-case
  .github/changelog/fix-user-option-outbox
  .github/changelog/fix-wp-error-id
  .github/changelog/improved-query-code
  .github/changelog/update-docs-pr-changelog-composer
  CHANGELOG.md
  activitypub.php
  readme.txt
Labels: Release

#1479 Changelog: allow generating a changelog entry from the PR description in a fork, too.
  .github/changelog/fix-changelog-workflow-forks
  .github/workflows/changelog.yml
Labels: [Type] Bug, Actions, github-actions, [Status] Needs review

#1474 Outbox: Add support for full activities
  .github/changelog/1474-from-description
  includes/activity/class-activity.php
  includes/class-cli.php
  includes/class-migration.php
  includes/collection/class-outbox.php
  includes/functions.php
  tests/includes/class-test-query.php
  tests/includes/class-test-scheduler.php
  tests/includes/collection/class-test-outbox.php
  tests/includes/handler/class-test-follow.php
  tests/includes/rest/class-test-outbox-controller.php
  tests/includes/scheduler/class-test-actor.php
Labels: [Feature] Collections

#1482 Changelog: invite external contributors to add changelog file
  .github/workflows/changelog.yml
Labels: [Type] Bug, Actions, Skip Changelog, github-actions, [Status] Needs review

#1413 Move: Differentiate between `internal` and `external` `Move`
  .github/changelog/add-inherit-activity
  includes/class-move.php
  tests/includes/class-test-handler.php
  tests/includes/class-test-move.php
Labels: [Status] In Progress, [Feature] Collections

#1483 Changelog: don't post duplicate comments for external contributors
  .github/workflows/changelog.yml
Labels: [Type] Bug, Actions, Skip Changelog, github-actions, [Status] Needs review

#1489 Auto-changelog: use a custom PAT instead of default GITHUB_TOKEN
  .github/workflows/changelog.yml
Labels: [Type] Bug, Actions, Skip Changelog, github-actions, [Status] Needs review

#1488 Fixed: Do not escape slashes in `json_encode`
  .github/changelog/1488-from-description
  includes/activity/class-generic-object.php
Labels: [Type] Bug, php

#1485 Interaction: Fix deleting comments
  .github/changelog/1485-from-description
  includes/collection/class-interactions.php
  includes/handler/class-delete.php
  tests/includes/handler/class-test-delete.php
Labels: [Feature] Collections

#1487 Fix site-health check
  .github/changelog/1487-from-description
  includes/wp-admin/class-health-check.php
Labels: [Type] Bug, php

#1492 Gardening: Automatically add `[Feature] WP Admin`
  .github/workflows/gardening.yml
Labels: Actions, Skip Changelog

#1484 Fix PHPStan errors
  includes/activity/class-base-object.php
  includes/activity/class-generic-object.php
  includes/class-comment.php
  includes/class-notification.php
  includes/collection/class-extra-fields.php
  includes/collection/class-interactions.php
  includes/functions.php
  includes/handler/class-announce.php
  includes/handler/class-create.php
  includes/handler/class-follow.php
  includes/handler/class-like.php
  includes/model/class-application.php
  includes/model/class-blog.php
  includes/model/class-follower.php
  includes/model/class-user.php
  includes/rest/class-actors-inbox-controller.php
  includes/rest/class-inbox-controller.php
  includes/rest/class-interaction-controller.php
  includes/rest/class-nodeinfo-controller.php
  includes/rest/class-server.php
  includes/transformer/class-activity-object.php
  includes/transformer/class-factory.php
  includes/transformer/class-post.php
  includes/wp-admin/class-admin.php
  includes/wp-admin/class-blog-settings-fields.php
  integration/class-enable-mastodon-apps.php
  integration/class-nodeinfo.php
  templates/activitypub-json.php
  templates/admin-header.php
  templates/new-follower-email.php
Labels: [Status] In Progress, [Focus] Compatibility, Skip Changelog, [Feature] Collections, [Feature] WP Admin

#1496 Add cursor-rules
  .cursor/rules/general.mdc
  .cursor/rules/wordpress-php-cursor-rules.mdc
  .distignore
Labels: [Type] Janitorial, Skip Changelog

#1503 Revert "Add cursor-rules (#1496)"
  .cursor/rules/general.mdc
  .cursor/rules/wordpress-php-cursor-rules.mdc
  .distignore
  .gitignore
Labels: [Type] Janitorial, [Type] Revert, Skip Changelog

#1500 Fix: Announces
  .github/changelog/1500-from-description
  includes/class-scheduler.php
  tests/includes/class-test-scheduler.php
Labels: [Type] Bug, [Status] In Progress

#1511 Onboarding: Redirect to "Welcome" page after plugin activation.
  .github/changelog/1511-from-description
  activitypub.php
Labels: [Type] Feature, [Feature] Onboarding

#1504 Onboarding: Allow skipping the welcome page
  .github/changelog/1504-from-description
  assets/css/activitypub-admin.css
  includes/wp-admin/class-settings.php
  includes/wp-admin/class-welcome-fields.php
Labels: [Status] In Progress, [Feature] WP Admin, [Feature] Onboarding

#1512 Fix: Set proper default, to show Welcome screen by default
  includes/class-activitypub.php
  includes/wp-admin/class-settings.php
Labels: Skip Changelog, [Feature] WP Admin

#1395 Add interaction settings
  .github/changelog/add-reaction-setting
  includes/class-activitypub.php
  includes/class-comment.php
  includes/handler/class-announce.php
  includes/handler/class-like.php
  includes/wp-admin/class-settings-fields.php
  tests/includes/collection/class-test-interactions.php
Labels: [Feature] WP Admin

#1520 Fix: Delete Undone comments instead of trashing them
  .github/changelog/1520-from-description
  includes/handler/class-undo.php
Labels: [Type] Bug

#1517 Fix: Do not send self-replies
  .github/changelog/1517-from-description
  includes/class-dispatcher.php
  tests/includes/class-test-dispatcher.php
Labels: [Type] Bug

#1502 Move: Add a Mastodon importer
  .github/changelog/1502-from-description
  activitypub.php
  includes/wp-admin/import/class-mastodon.php
  includes/wp-admin/import/load.php
Labels: [Feature] WP Admin

#1525 Importer: Format import count number.
  .github/workflows/gardening.yml
  includes/wp-admin/import/class-mastodon.php
Labels: Actions, Skip Changelog, [Feature] WP Admin

#1527 Tests: Reduce chance of time offsets
  tests/includes/scheduler/class-test-actor.php
Labels: Skip Changelog
