Repository Automattic/wordpress-activitypub, pull requests merged in 2025-07, with the labels that each got.

#1878 Re-Add ActivityPub CLI extension
  .github/changelog/1878-from-description
  .github/workflows/gardening.yml
  activitypub.php
Labels: Actions

#1879 Add `follow` CLI command
  includes/class-cli.php
Labels: [Feature] CLI

#1880 Follow: Set local user as actor in Accept activities
  includes/handler/class-follow.php
  tests/includes/handler/class-test-follow.php
Labels: Skip Changelog

#1886 Signature: Fix server request formatting
  includes/class-signature.php
Labels: Skip Changelog

#1892 Signature: Don't use param as component
  includes/signature/class-http-message-signature.php
Labels: Skip Changelog, [Feature] Signature

#1899 Federation: Swap doc URLs
  FEDERATION.md
Labels: Docs, Skip Changelog

#1901 Signature: Use lowercase key in Content-Digest
  includes/signature/class-http-message-signature.php
  tests/includes/class-test-signature.php
Labels: Skip Changelog, [Feature] Signature

#1903 Signature: Examine public key when no algorithm passed
  includes/signature/class-http-message-signature.php
  tests/includes/class-test-signature.php
Labels: Skip Changelog, [Feature] Signature

#1863 Signature: Improved naming consistency
  includes/class-signature.php
  includes/signature/class-http-message-signature.php
  includes/signature/class-http-signature-draft.php
  includes/signature/interface-http-signature.php
  tests/includes/class-test-signature.php
  tests/includes/rest/class-test-actors-inbox-controller.php
Labels: Skip Changelog, [Feature] Signature

#1906 Signature: Check for positive case in host support
  includes/class-signature.php
  tests/includes/class-test-signature.php
Labels: Skip Changelog

#1911 Release 7.0.0
  .github/changelog/1630-from-description
  .github/changelog/1759-from-description
  .github/changelog/1802-from-description
  .github/changelog/1803-from-description
  .github/changelog/1805-from-description
  .github/changelog/1806-from-description
  .github/changelog/1807-from-description
  .github/changelog/1809-from-description
  .github/changelog/1810-from-description
  .github/changelog/1811-from-description
  .github/changelog/1812-from-description
  .github/changelog/1814-from-description
  .github/changelog/1819-from-description
  .github/changelog/1820-from-description
  .github/changelog/1821-from-description
  .github/changelog/1822-from-description
  .github/changelog/1826-from-description
  .github/changelog/1829-from-description
  .github/changelog/1832-from-description
  .github/changelog/1834-from-description
  .github/changelog/1835-from-description
  .github/changelog/1837-from-description
  .github/changelog/1839-from-description
  .github/changelog/1841-from-description
  .github/changelog/1846-from-description
  .github/changelog/1847-from-description
  .github/changelog/1848-from-description
  .github/changelog/1849-from-description
  .github/changelog/1857-from-description
  .github/changelog/1858-from-description
  .github/changelog/1862-from-description
  .github/changelog/1865-from-description
  .github/changelog/1866-from-description
  .github/changelog/1868-from-description
  .github/changelog/1873-from-description
  .github/changelog/1877-from-description
  .github/changelog/1878-from-description
  .github/changelog/1887-from-description
  .github/changelog/1889-from-description
  .github/changelog/1893-from-description
  .github/changelog/1895-from-description
  CHANGELOG.md
  activitypub.php
  includes/class-migration.php
  includes/class-shortcodes.php
  includes/class-signature.php
  includes/collection/class-followers.php
  readme.txt
Labels: [Feature] Collections, Release

#1907 Query: Don't double-query posts
  .github/changelog/1907-from-description
  includes/collection/class-actors.php
  includes/collection/class-followers.php
  includes/collection/class-following.php
  tests/includes/class-test-comment.php
Labels: [Feature] Collections

#1913 Followers: Make table look more like Core
  .github/changelog/1913-from-description
  assets/css/activitypub-admin.css
  includes/table/class-followers.php
  includes/wp-admin/class-admin.php
  includes/wp-admin/class-settings.php
  templates/blog-followers-list.php
  templates/followers-list.php
  templates/user-followers-list.php
Labels: [Feature] WP Admin

#1917 Release 7.0.1
  .github/changelog/1915-from-description
  CHANGELOG.md
  activitypub.php
  readme.txt
Labels: Skip Changelog

#1921 Deprecate `activitypub_rest_following` filter
  includes/rest/class-following-controller.php
Labels: Skip Changelog, [Feature] REST API

#1918 Fix Followers Count: `Followers::count_followers()`
  .github/changelog/1918-from-description
  includes/collection/class-followers.php
  tests/includes/collection/class-test-followers.php
Labels: [Feature] Collections

#1931 Fix Accept handling for outgoing Follow requests
  .github/changelog/1931-from-description
  includes/collection/class-outbox.php
  includes/handler/class-accept.php
  tests/includes/collection/class-test-following.php
Labels: [Feature] Collections

#1933 Followers: Row action and update notice
  includes/table/class-followers.php
  includes/table/class-following.php
Labels: Skip Changelog

#1936 Fix `Undefined array key "keyId"` error
  includes/signature/class-http-signature-draft.php
Labels: Skip Changelog, [Feature] Signature

#1940 Fix: readme of modal module
  src/shared/modal/README.md
Labels: Docs, OSS Citizen, Skip Changelog, [Focus] Editor

#1934 Following: Add info section about follow requests
  templates/following-list.php
Labels: Skip Changelog

#1951 Settings: Only initiate table that's needed
  includes/wp-admin/class-admin.php
  includes/wp-admin/class-menu.php
Labels: Skip Changelog, [Feature] WP Admin

#1952 Missed to add a param!
  includes/collection/class-followers.php
Labels: Skip Changelog, [Feature] Collections

#1954 Follower: Fix missing ID warnings
  includes/table/class-followers.php
  includes/table/class-following.php
Labels: Skip Changelog

#1956 Fix duplicate admin-notices
  includes/table/class-followers.php
  includes/table/class-following.php
Labels: Skip Changelog

#1961 Admin-Notices: Adapt width of settings-site
  assets/css/activitypub-admin.css
Labels: Skip Changelog

#1939 Tables: Combine actor search term sanitization
  includes/table/class-followers.php
  includes/table/class-following.php
  includes/table/trait-actor-list-table.php
Labels: Skip Changelog

#1974 Normalize Account-Aliases to always use the ID
  .github/changelog/1974-from-description
  includes/class-activitypub.php
  includes/class-sanitize.php
  includes/wp-admin/class-blog-settings-fields.php
  includes/wp-admin/class-settings.php
  includes/wp-admin/class-user-settings-fields.php
Labels: [Feature] WP Admin

#1981 Following: Replace feature switch `filter` with `option`
  includes/debug.php
  includes/wp-admin/class-advanced-settings-fields.php
  includes/wp-admin/class-menu.php
  includes/wp-admin/class-settings.php
  includes/wp-admin/import/load.php
Labels: Skip Changelog, [Feature] WP Admin, [Feature] Import

#1983 Settings: Disable screen options on followers/following tabs
  includes/wp-admin/class-screen-options.php
Labels: Skip Changelog, [Feature] WP Admin

#1986 Always remove filter `maybe_double_knock` `http_response` filter!
  includes/class-signature.php
Labels: Skip Changelog

#1992 Release 7.1.0
  .github/changelog/1900-from-description
  .github/changelog/1907-from-description
  .github/changelog/1909-from-description
  .github/changelog/1913-from-description
  .github/changelog/1916-from-description
  .github/changelog/1918-from-description
  .github/changelog/1919-from-description
  .github/changelog/1920-from-description
  .github/changelog/1922-from-description
  .github/changelog/1925-from-description
  .github/changelog/1928-from-description
  .github/changelog/1930-from-description
  .github/changelog/1931-from-description
  .github/changelog/1932-from-description
  .github/changelog/1942-from-description
  .github/changelog/1943-from-description
  .github/changelog/1946-from-description
  .github/changelog/1959-from-description
  .github/changelog/1973-from-description
  .github/changelog/1974-from-description
  .github/changelog/1979-from-description
  .github/changelog/1980-from-description
  .github/changelog/1985-from-description
  .github/changelog/1988-from-description
  CHANGELOG.md
  activitypub.php
  includes/collection/class-followers.php
  includes/functions.php
  includes/rest/class-following-controller.php
  readme.txt
Labels: [Feature] Collections, Release, [Feature] REST API

#2005 Rebuild JS and linting
  .extract-wp-hooks.json
  .github/workflows/extract-wp-hooks.yml
  build/editor-plugin/plugin.asset.php
  build/editor-plugin/plugin.js
  build/follow-me/index.asset.php
  build/follow-me/index.js
  build/follow-me/view.asset.php
  build/follow-me/view.js
  build/followers/index.asset.php
  build/followers/index.js
  build/followers/view.asset.php
  build/followers/view.js
  build/reactions/index.asset.php
  build/reactions/index.js
  build/reactions/view.asset.php
  build/reactions/view.js
  build/remote-reply/view.asset.php
  build/remote-reply/view.js
  build/reply-intent/plugin.asset.php
  build/reply-intent/plugin.js
  build/reply/index.asset.php
  build/reply/index.js
Labels: Actions, Skip Changelog

#2002 Fix: Correct linking from followers to the following list
  .github/changelog/2002-from-description
  includes/wp-admin/table/class-followers.php
Labels: [Feature] WP Admin

#2003 Followers List: "Follow back" Action
  .github/changelog/2003-from-description
  includes/wp-admin/table/class-followers.php
Labels: [Feature] WP Admin

#2012 Tables: Refactor action URL generation
  includes/wp-admin/table/class-followers.php
  includes/wp-admin/table/class-following.php
  includes/wp-admin/table/trait-actor-list-table.php
Labels: Skip Changelog, [Feature] WP Admin

#2014 Add .claude to .gitignore
  .gitignore
Labels: Skip Changelog

#2013 Tables: Minor code changes
  includes/wp-admin/table/class-followers.php
  includes/wp-admin/table/class-following.php
  includes/wp-admin/table/trait-actor-list-table.php
Labels: Skip Changelog, [Feature] WP Admin

#2019 Post: Set activitypub request context for content render (alternate solution)
  .github/changelog/2019-from-description
  includes/class-blocks.php
  includes/transformer/class-base.php
  includes/transformer/class-post.php
  src/follow-me/render.php
  src/remote-reply/render.php
  tests/includes/transformer/class-test-post.php
Labels: [Block] Follow Me, [Block] Remote Reply, [Focus] Editor

#2021 Change environment for unittesting to `staging`
  .distignore
  .github/changelog/2021-from-description
  .github/workflows/phpunit.yml
  .wp-env.json
  activitypub.php
  local/class-cli.php
  local/load.php
  tests/includes/class-test-activitypub.php
Labels: Actions

#2022 Fix surge integration and tests
  integration/class-surge.php
  integration/load.php
  tests/integration/class-test-surge.php
Labels: [Focus] Compatibility, Skip Changelog

#2023 Following: Load polling only on following tables
  includes/wp-admin/class-heartbeat.php
Labels: Skip Changelog, [Feature] WP Admin

#2030 Release 7.2.0
  .github/changelog/1982-from-description
  .github/changelog/1994-from-description
  .github/changelog/1995-from-description
  .github/changelog/1996-from-description
  .github/changelog/2001-from-description
  .github/changelog/2002-from-description
  .github/changelog/2003-from-description
  .github/changelog/2010-from-description
  .github/changelog/2015-from-description
  .github/changelog/2019-from-description
  .github/changelog/2021-from-description
  .github/changelog/2028-from-description
  CHANGELOG.md
  activitypub.php
  includes/transformer/class-post.php
  readme.txt
Labels: Release

#2032 Defer signature verification on local env
  local/load.php
Labels: Skip Changelog

#2036 Fix .wp-env.json port configuration to enable loopback requests
  .wp-env.json
  tests/includes/class-test-functions.php
  tests/includes/class-test-move.php
  tests/includes/collection/class-test-actors.php
  tests/includes/collection/class-test-outbox.php
  tests/includes/collection/class-test-replies.php
  tests/includes/model/class-test-blog.php
  tests/includes/model/class-test-user.php
  tests/includes/rest/class-test-webfinger-controller.php
Labels: Skip Changelog

#2039 Starter Kits: Add support for list of IDs
  .github/changelog/2039-from-description
  includes/wp-admin/import/class-starter-kit.php
Labels: [Feature] WP Admin, [Feature] Import
