Repository Automattic/wordpress-activitypub, pull requests merged in 2025-09, with the labels that each got.

#2123 Optimize GitHub Actions workflows
  .github/workflows/deploy.yml
  .github/workflows/format.yml
  .github/workflows/phpcs.yml
Labels: Actions, Skip Changelog

#2136 Add Yoast SEO integration for media pages site health check
  .github/changelog/2136-from-description
  integration/class-yoast-seo.php
  integration/load.php
  tests/integration/class-test-yoast-seo.php
Labels: [Focus] Compatibility

#2122 Add precommit hook with automated formatting
  .distignore
  .githooks/pre-commit
  .gitignore
  .prettierignore
  bin/precommit/check-unused-imports.js
  bin/precommit/sort-php-imports.js
  package.json
Labels: [Block] Followers, [Focus] Compatibility, Skip Changelog, [Block] Remote Reply, [Focus] Editor, [Feature] Collections, [Block] Reactions, [Feature] Reactions, [Feature] WP Admin, [Feature] Import, [Feature] Health Check, [Feature] REST API

#2148 Move `Activity-Object-Type` setting to advanced settings
  .github/changelog/2148-from-description
  includes/class-options.php
  includes/wp-admin/class-advanced-settings-fields.php
  includes/wp-admin/class-settings-fields.php
  includes/wp-admin/class-settings.php
Labels: [Status] In Progress, [Feature] WP Admin

#2151 Refactor remote actor handling to Remote_Actors class
  build/followers/render.php
  includes/class-activitypub.php
  includes/class-migration.php
  includes/class-sanitize.php
  includes/class-scheduler.php
  includes/class-signature.php
  includes/class-webfinger.php
  includes/collection/class-actors.php
  includes/collection/class-blocked-actors.php
  includes/collection/class-followers.php
  includes/collection/class-following.php
  includes/collection/class-remote-actors.php
  includes/functions.php
  includes/handler/class-accept.php
  includes/handler/class-delete.php
  includes/handler/class-move.php
  includes/handler/class-reject.php
  includes/handler/class-update.php
  includes/model/class-follower.php
  includes/rest/class-followers-controller.php
  includes/rest/class-following-controller.php
  includes/scheduler/class-actor.php
  includes/signature/class-http-message-signature.php
  includes/signature/class-http-signature-draft.php
  includes/wp-admin/table/class-blocked-actors.php
  includes/wp-admin/table/class-followers.php
  includes/wp-admin/table/class-following.php
  integration/class-enable-mastodon-apps.php
  src/followers/render.php
  templates/block-confirmation.php
  templates/bulk-block-confirmation.php
  tests/includes/class-test-hashtag.php
  tests/includes/class-test-migration.php
  tests/includes/class-test-move.php
  tests/includes/class-test-scheduler.php
  tests/includes/class-test-search.php
  tests/includes/collection/class-test-actors.php
  tests/includes/collection/class-test-followers.php
  tests/includes/collection/class-test-following.php
  tests/includes/collection/class-test-remote-actors.php
  tests/includes/handler/class-test-accept.php
  tests/includes/handler/class-test-move.php
  tests/includes/handler/class-test-reject.php
  tests/includes/handler/class-test-update.php
  tests/includes/model/class-test-follower.php
  tests/includes/rest/class-test-followers-controller.php
  tests/includes/rest/class-test-following-controller.php
  tests/includes/scheduler/class-test-actor.php
  tests/includes/wp-admin/table/class-test-blocked-actors.php
  tests/includes/wp-admin/table/class-test-followers.php
  tests/includes/wp-admin/table/class-test-following.php
Labels: [Block] Followers, [Status] In Progress, [Focus] Compatibility, [Type] Janitorial, Skip Changelog, [Focus] Editor, [Feature] Collections, [Feature] WP Admin, [Feature] REST API, [Feature] Signature

#2195 Change 'implements' to array in generator definitions
  .github/changelog/2195-from-description
  includes/model/class-blog.php
  includes/model/class-user.php
  includes/rest/class-actors-controller.php
Labels: [Status] In Progress, [Feature] REST API

#2193 Add Yoast SEO author archives site health test
  .github/changelog/2193-from-description
  integration/class-yoast-seo.php
Labels: [Focus] Compatibility

#2227 Add comprehensive unit tests for Server class
  includes/rest/class-server.php
  tests/includes/rest/class-test-actors-inbox-controller.php
  tests/includes/rest/class-test-server.php
Labels: Skip Changelog, [Feature] REST API

#2226 Add following meta key to Jetpack sync allowlist
  .github/changelog/2226-from-description
  integration/class-jetpack.php
Labels: [Focus] Compatibility

#2235 Add `fetch_by_acct` and `fetch_by_various` methods to Remote_Actors
  .github/changelog/2235-from-description
  includes/collection/class-remote-actors.php
  includes/functions.php
  tests/includes/collection/class-test-remote-actors.php
Labels: [Status] In Progress, [Feature] Collections

#2248 Update deploy workflow to trigger on release
  .github/workflows/deploy.yml
Labels: Actions, [Type] Janitorial, Skip Changelog

#2247 Add external link icon to Jetpack reader feed link
  assets/css/activitypub-admin.css
  integration/class-jetpack.php
Labels: [Focus] Compatibility, Skip Changelog

#2250 Fix Reader URL generation for WPCOM environment
  integration/class-jetpack.php
  tests/integration/class-test-jetpack.php
Labels: [Focus] Compatibility, Skip Changelog
